server:
  port: 8502

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: ${management.contextPath}/health
        health-check-interval: 15s
        instance-id: service-hi
  application:
    name: service-hi