server:
  port: 8762
spring:
  profiles:
    active: peer2
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
    fetch-registry: false
    register-with-eureka: false