# 端口
#server.port=8763
#spring.application.name=say-hello
# 服务名称
#eureka.client.service-url.defaultZone=http://peer:8761/eureka/
# 续约更新时间间隔（默认30秒）
#eureka.instance.lease-renewal-interval-in-seconds=30
# 续约到期时间（默认90秒）
#eureka.instance.lease-expiration-duration-in-seconds=30
server:
  port: 8763
spring:
  application:
    name: say-hello
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/